### ISSUE TITLE
GetResponses() And it's resulting answers are null/0 valued.

### ISSUE THREAD

**Issue by omnoms** [bcemmett/SurveyMonkeyApi#1]
I can get stuff like details about the survey, titles, nicknames, etc.. but when I dig down and do a GetResponses() and check the resulting values, they're 0 or null (as if by default) while they're not when checking through the web-front/standard GUI.

The only value that is populated is "Row". What I'm trying to do is loop through all the responses and do an average on the values.

![image](https://cloud.githubusercontent.com/assets/7261863/5834281/09820702-a15c-11e4-94be-9be5a07e2837.png)

**Comment by omnoms** [comment]
The other values in the ResponseAnswer were quite useless. Getting the row number, I had to reiterate over the survey details to match the Row with the AnswerId in GetSurveyDetails().Questions[_].Answers[_]

**Comment by bcemmett** [comment]
The data you're seeing should be exactly as offered by the API. It returns details about the survey from GetSurveyDetails(), and the details about responses from GetResponses(). As you say it's necessary to match up to data from the 2 endpoints. While the Col and ColChoice values aren't useful for the question type you were processing, they are used to match up data for other question types.

The library has a method sm.FillMissingSurveyInformation(survey) which can do all this for you. It will call all other endpoints needed for you to get the relevant data, and create an object survey.Responses[].Questions[].ProcessedAnswer, which has details of the question and the Response by matching up the ResponseAnswer objects with survey.Questions[].Answers[]. Just call it after you have a Survey object from sm.GetSurveyList(). It will do this mapping for all the different question types and handles some unexpected cases, so it's likely easier than writing your own logic to do the mapping. The second half of https://www.simple-talk.com/blogs/2014/08/10/new-net-library-for-accessing-the-survey-monkey-api/ describes this.

**Comment by omnoms** [comment]
Thank you =) 

I will have a look at FillMissingSurveyInformation if I need more data than I am currently using.

I ended up doing this;

``` C#
                List<long> rList = sm.GetRespondentList(sm_SurveyId).Select(resp => resp.RespondentId).ToList();
                List<Response> responses = sm.GetResponses(sm_SurveyId, rList);
                var sDetails = sm.GetSurveyDetails(sm_SurveyId);
                List<SurveyMonkey.Answer> aws = sDetails.Questions[0].Answers;
                int total = 0;
                for (int j = 0; j < responses.Count(); j++) { 
                    SurveyMonkey.ResponseAnswer ra = responses[j].Questions[0].Answers[0];
                    SurveyMonkey.Answer aw = aws.Single(a => a.AnswerId == ra.Row);
                    total += aw.Position;
                }
                Console.WriteLine("Average NKI: " + total/responses.Count());          
```
