### ISSUE TITLE
Public API should be exposed through interfaces to allow easy mocking

### ISSUE THREAD

**Issue by rubberduck203** [bcemmett/SurveyMonkeyApi#3]
Currently, the public API is exposed through concrete implementations of... well... everything. This makes it difficult to fake/mock calls so that tests don't actually hit SurveyMonkey's API. 

Would you be open to someone extracting interfaces and submitting a PR?

**Comment by bcemmett** [comment]
Absolutely, please do :-)

**Comment by rubberduck203** [comment]
Cool. Will do.

**Comment by bcemmett** [comment]
Thanks for the PR! This is now on NuGet as v1.3.0.
